# API Endpoint
@baseUrl = http://localhost:3000
# ここは各自デプロイした結果によって異なります。
# @baseUrl = https://hono-vertexai-image-tbj5qgjmvq-uc.a.run.app

### GET /
GET {{baseUrl}}/

### GET /health
GET {{baseUrl}}/health

### POST /agentVertexAI
POST {{baseUrl}}/agentVertexAI
Content-Type: application/json

{
  "prompt": "Please tell me the latest news about Web3 or cryptocurrency or blockchain. I will lend some token on base sepolia.",
  "operation": "SocialTrend"
}

## "prompt": "If I want to grow my assets by swapping, lending, or staking cryptocurrencies, what should I do?",
##  "prompt": "Web3に関するトレンド情報を集めてください。",
##  "operation": "SocialTrend"
##  "prompt": "Web3に関する最新のニュースを集めてください。",
##  "operation": "NewsAndFundamentals"
##  "operation": "RiskManagement"
##  "operation": "PerformanceMonitoring"
##  "operation": "AnalysisAndReasoning"
##  "operation": "DeFi"

### POST /runChatGroqAgent
POST {{baseUrl}}/runChatGroqAgent
Content-Type: application/json

{
  "prompt": "アカウントが Arbitrum Sepolia ネットワークで 5 USDC以上保有している場合、 5 USDCを貸し出してください。 結果に以下を含めてください: - アカウントの新しい担保状況 - トランザクションハッシュ - トランザクションステータス"
}


## "prompt": "アカウントが Holeskyで 10ETH以上保有している場合、 10ETHを使ってステーキングしてください。 結果に以下を含めてください: - アカウントの新しい担保状況 - トランザクションハッシュ - トランザクションステータス"
## "prompt": "アカウントが Arbitrum Sepolia ネットワークで 5 USDC以上保有している場合、 5 USDCを貸し出してください。 結果に以下を含めてください: - アカウントの新しい担保状況 - トランザクションハッシュ - トランザクションステータス"


### POST /runCryptOpenAIAgent
POST {{baseUrl}}/runCryptOpenAIAgent
Content-Type: application/json

{
  "prompt": "Web3に関する最新のニュースを集めてください。",
  "operation": "NewsAndFundamentals"
}

## "prompt": "アカウントが Arbitrum Sepolia ネットワークで 5 USDC以上保有している場合、 5 USDCを貸し出してください。 結果に以下を含めてください: - アカウントの新しい担保状況 - トランザクションハッシュ - トランザクションステータス"
## "prompt": "アカウントが Holeskyで 1stETH以上保有している場合、 1stETHをリステーキングしてください。 結果に以下を含めてください: - アカウントの新しい担保状況 - トランザクションハッシュ - トランザクションステータス"
