# API Endpoint
@baseUrl = http://localhost:3000
# ここは各自デプロイした結果によって異なります。
# @baseUrl = https://hono-vertexai-image-tbj5qgjmvq-uc.a.run.app

### GET /
GET {{baseUrl}}/

### GET /health
GET {{baseUrl}}/health

### POST /agentVertexAI
POST {{baseUrl}}/agentVertexAI
Content-Type: application/json

{
  "prompt": "アカウントが sepolia ネットワークで50 USDC以上の USDCを保有している場合、 WETHにSwapしてください。 結果に以下を含めてください: - アカウントの新しい担保状況 - トランザクションハッシュ - トランザクションステータス"
}

### POST /runChatGroqAgent
POST {{baseUrl}}/runChatGroqAgent
Content-Type: application/json

{
  "prompt": "アカウントが Arbitrum Sepolia ネットワークで 5 USDC以上保有している場合、 5 USDCを貸し出してください。 結果に以下を含めてください: - アカウントの新しい担保状況 - トランザクションハッシュ - トランザクションステータス"
}


## "prompt": "アカウントが Holeskyで 10ETH以上保有している場合、 10ETHを使ってステーキングしてください。 結果に以下を含めてください: - アカウントの新しい担保状況 - トランザクションハッシュ - トランザクションステータス"
## "prompt": "アカウントが Arbitrum Sepolia ネットワークで 5 USDC以上保有している場合、 5 USDCを貸し出してください。 結果に以下を含めてください: - アカウントの新しい担保状況 - トランザクションハッシュ - トランザクションステータス"


### POST /runCryptOpenAIAgent
POST {{baseUrl}}/runCryptOpenAIAgent
Content-Type: application/json

{
  "prompt": "アカウントが Holeskyで 1stETH以上保有している場合、 1stETHをリステーキングしてください。 結果に以下を含めてください: - アカウントの新しい担保状況 - トランザクションハッシュ - トランザクションステータス"
}

## "prompt": "アカウントが Arbitrum Sepolia ネットワークで 5 USDC以上保有している場合、 5 USDCを貸し出してください。 結果に以下を含めてください: - アカウントの新しい担保状況 - トランザクションハッシュ - トランザクションステータス"
## "prompt": "アカウントが Holeskyで 1stETH以上保有している場合、 1stETHをリステーキングしてください。 結果に以下を含めてください: - アカウントの新しい担保状況 - トランザクションハッシュ - トランザクションステータス"
